<?php
/**
 * Executive Consolidated Monthly Report View (GPS Attendance + Tender KPI Tracker)
 * Company: The Bridge Business Alliance (TBBA)
 * Language: Fully English
 */
require_once __DIR__ . '/../../core/Auth.php';
Auth::requireLogin();
$currentUser = Auth::user();
include __DIR__ . '/../layouts/header.php';
include __DIR__ . '/../layouts/sidebar.php';
include __DIR__ . '/../layouts/navbar.php';
?>

<!-- Print-Only Header Logo & Corporate Info -->
<div class="print-header" style="display: none; border-bottom: 2px solid #0F172A; padding-bottom: 16px; margin-bottom: 24px; text-align: center;">
    <h1 style="font-size: 24px; font-weight: 800; color: #0F172A; margin: 0 0 4px; letter-spacing: 0.5px;">THE BRIDGE BUSINESS ALLIANCE (TBBA)</h1>
    <h2 style="font-size: 16px; font-weight: 700; color: #475569; margin: 0 0 8px; text-transform: uppercase;">EXECUTIVE CONSOLIDATED MONTHLY REPORT (ATTENDANCE & TENDER KPI)</h2>
    <p style="font-size: 12px; color: #64748B; margin: 0;">Reporting Period: <strong><?= date('F Y', mktime(0, 0, 0, $selectedMonth, 1, $selectedYear)) ?></strong> | Generated by: <strong><?= htmlspecialchars($currentUser['name']) ?></strong> (<?= strtoupper($currentUser['role']) ?>)</p>
</div>

<!-- Report workspace header and controls -->
<div class="card no-print module-page-header report-overview" style="margin-bottom: 24px; background: linear-gradient(135deg, #0F172A 0%, #1E3A8A 100%); color: #FFFFFF; border: none; border-radius: 20px; padding: 32px; box-shadow: 0 10px 25px -5px rgba(15, 23, 42, 0.3); display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 20px;">
    <div class="report-overview-main">
    <div style="flex: 1; min-width: 300px;">
        <h1 style="font-size: 26px; font-weight: 800; margin: 0 0 8px; color: #FFFFFF; display: flex; align-items: center; gap: 10px;">
            <i class="fa-solid fa-chart-line"></i>
            <span>Monthly Performance Report</span>
        </h1>
        <p style="font-size: 14px; color: #CBD5E1; margin: 0; max-width: 680px; line-height: 1.6;">
            Attendance, staff discipline and tender performance for <strong><?= date('F Y', mktime(0, 0, 0, $selectedMonth, 1, $selectedYear)) ?></strong>.
        </p>
    </div>

    <div class="report-export-actions" style="display: flex; gap: 12px; flex-wrap: wrap;">
        <a href="index.php?page=reports&export=csv&month=<?= $selectedMonth ?>&year=<?= $selectedYear ?>&department_id=<?= $selectedDept ?? '' ?>" 
           class="btn" style="background: #10B981; color: #FFF; border: none; border-radius: 12px; padding: 12px 20px; font-weight: 700; font-size: 13px; display: inline-flex; align-items: center; gap: 8px; box-shadow: 0 4px 12px rgba(16,185,129,0.3); transition: all 0.2s ease; text-decoration: none;">
            <i class="fa-solid fa-file-csv"></i> CSV
        </a>
        <a href="index.php?page=reports&export=pdf&month=<?= $selectedMonth ?>&year=<?= $selectedYear ?>&department_id=<?= $selectedDept ?? '' ?>" 
           class="btn" style="background: #2563EB; color: #FFF; border: none; border-radius: 12px; padding: 12px 20px; font-weight: 700; font-size: 13px; display: inline-flex; align-items: center; gap: 8px; box-shadow: 0 4px 12px rgba(37,99,235,0.3); transition: all 0.2s ease; text-decoration: none;">
            <i class="fa-solid fa-file-pdf"></i> PDF
        </a>
        <a href="index.php?page=reports&export=print&month=<?= $selectedMonth ?>&year=<?= $selectedYear ?>&department_id=<?= $selectedDept ?? '' ?>" target="_blank"
           class="btn" style="background: rgba(255,255,255,0.15); color: #FFF; border: 1px solid rgba(255,255,255,0.3); border-radius: 12px; padding: 12px 20px; font-weight: 700; font-size: 13px; display: inline-flex; align-items: center; gap: 8px; backdrop-filter: blur(10px); transition: all 0.2s ease; text-decoration: none; cursor: pointer;">
            <i class="fa-solid fa-print"></i> Print
        </a>
    </div>
    </div>

<!-- Filter Bar -->
<div class="report-filterbar">
    <form method="GET" action="index.php" class="report-filter-form" style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 16px;">
        <input type="hidden" name="page" value="reports">
        
        <div class="report-filter-fields" style="display: flex; align-items: center; gap: 16px; flex-wrap: wrap; flex: 1;">
            <div>
                <label style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; display: block; margin-bottom: 6px;">Month</label>
                <select name="month" class="form-control" style="border-radius: 10px; font-weight: 600; font-size: 13px; padding: 8px 14px; border: 1px solid #CBD5E1; min-width: 150px; background: #F8FAFC;">
                    <?php
                    for ($m = 1; $m <= 12; $m++) {
                        $sel = ($m === $selectedMonth) ? 'selected' : '';
                        $mName = date('F', mktime(0, 0, 0, $m, 1));
                        echo "<option value=\"{$m}\" {$sel}>{$mName}</option>";
                    }
                    ?>
                </select>
            </div>

            <div>
                <label style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; display: block; margin-bottom: 6px;">Year</label>
                <select name="year" class="form-control" style="border-radius: 10px; font-weight: 600; font-size: 13px; padding: 8px 14px; border: 1px solid #CBD5E1; min-width: 110px; background: #F8FAFC;">
                    <?php
                    $curYear = (int)date('Y');
                    for ($y = $curYear + 1; $y >= 2024; $y--) {
                        $sel = ($y === $selectedYear) ? 'selected' : '';
                        echo "<option value=\"{$y}\" {$sel}>{$y}</option>";
                    }
                    ?>
                </select>
            </div>

            <div>
                <label style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; display: block; margin-bottom: 6px;">Department</label>
                <select name="department_id" class="form-control" style="border-radius: 10px; font-weight: 600; font-size: 13px; padding: 8px 14px; border: 1px solid #CBD5E1; min-width: 200px; background: #F8FAFC;">
                    <option value="">All Departments & Branches</option>
                    <?php foreach ($deptMap as $dId => $dName): ?>
                        <option value="<?= $dId ?>" <?= ($selectedDept === $dId) ? 'selected' : '' ?>><?= htmlspecialchars($dName) ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="report-filter-actions" style="display: flex; gap: 10px; align-self: flex-end;">
            <a href="index.php?page=reports" class="btn" style="background: #F1F5F9; color: #475569; border: 1px solid #CBD5E1; border-radius: 10px; padding: 9px 18px; font-weight: 600; font-size: 13px; text-decoration: none;">
                <i class="fa-solid fa-rotate-left"></i> Reset
            </a>
            <button type="submit" class="btn btn-primary" style="background: #2563EB; color: #FFF; border: none; border-radius: 10px; padding: 9px 24px; font-weight: 700; font-size: 13px; box-shadow: 0 4px 10px rgba(37,99,235,0.25);">
                <i class="fa-solid fa-check"></i> Apply
            </button>
        </div>
    </form>
</div>
</div>

<!-- Executive summary -->
<div class="executive-summary" style="gap: 20px; margin-bottom: 28px;">
    <!-- Card 1: Staff Assessed -->
    <div class="card module-stat-card" style="border-radius: 16px; border: 1px solid #E2E8F0; padding: 20px; background: #FFFFFF; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02);">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 12px;">
            <div>
                <span style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.5px;">Active Personnel</span>
                <div style="font-size: 28px; font-weight: 800; color: #0F172A; margin-top: 4px;"><?= $totalStaffCount ?></div>
            </div>
            <div style="width: 44px; height: 44px; border-radius: 12px; background: #EFF6FF; color: #2563EB; display: flex; align-items: center; justify-content: center; font-size: 18px;">
                <i class="fa-solid fa-users-viewfinder"></i>
            </div>
        </div>
        <div style="font-size: 12px; color: #64748B;">
            Assessed across <?= count($deptMap) ?> departments
        </div>
    </div>

    <!-- Card 2: Average Attendance Rate -->
    <div class="card module-stat-card" style="border-radius: 16px; border: 1px solid #E2E8F0; padding: 20px; background: #FFFFFF; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02);">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 12px;">
            <div>
                <span style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.5px;">Avg Attendance Rate</span>
                <div style="font-size: 28px; font-weight: 800; color: <?= $avgAttendanceRate >= 90 ? '#059669' : ($avgAttendanceRate >= 80 ? '#D97706' : '#DC2626') ?>; margin-top: 4px;">
                    <?= $avgAttendanceRate ?>%
                </div>
            </div>
            <div style="width: 44px; height: 44px; border-radius: 12px; background: #ECFDF5; color: #059669; display: flex; align-items: center; justify-content: center; font-size: 18px;">
                <i class="fa-solid fa-clock-rotate-left"></i>
            </div>
        </div>
        <div style="font-size: 12px; color: #64748B;">
            Present / On-Time vs Total Work Days
        </div>
    </div>

    <!-- Card 3: Tender performance -->
    <div class="card module-stat-card" style="border-radius: 16px; border: 1px solid #E2E8F0; padding: 20px; background: #FFFFFF; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02);">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 12px;">
            <div style="min-width:0;">
                <span style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.5px;">Tender Performance</span>
                <div class="report-money" style="font-size: 24px; font-weight: 800; color: #7C3AED; margin-top: 4px;">
                    RM <?= number_format($totalTendersValue, 2) ?>
                </div>
                <span style="display:block;margin-top:2px;color:#64748B;font-size:10px;font-weight:700;">Total tender value</span>
            </div>
            <div style="width: 44px; height: 44px; border-radius: 12px; background: #F5F3FF; color: #7C3AED; display: flex; align-items: center; justify-content: center; font-size: 18px;">
                <i class="fa-solid fa-file-signature"></i>
            </div>
        </div>
        <div class="report-profit-row">
            <span><i class="fa-solid fa-trophy"></i> Won profit</span>
            <strong style="color:<?= $totalWonMargin >= 0 ? '#059669' : '#DC2626' ?>;">
                <?= $totalWonMargin < 0 ? '-' : '' ?>RM <?= number_format(abs($totalWonMargin), 2) ?>
            </strong>
        </div>
        <div style="font-size: 11px; color: #64748B; margin-top:8px;">
            <?= $totalTendersCount ?> submitted · <?= $totalWonCount ?> won · Won revenue RM <?= number_format($totalWonRevenue, 2) ?>
        </div>
    </div>

    <!-- Card 4: Action Alerts -->
    <div class="card module-stat-card" style="border-radius: 16px; border: 1px solid #E2E8F0; padding: 20px; background: #FFFFFF; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.02);">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 12px;">
            <div>
                <span style="font-size: 11px; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.5px;">Discipline / KPI Alerts</span>
                <div style="font-size: 28px; font-weight: 800; color: #DC2626; margin-top: 4px;">
                    <?= $lateAlertsCount + $zeroTenderCount ?>
                </div>
            </div>
            <div style="width: 44px; height: 44px; border-radius: 12px; background: #FEF2F2; color: #DC2626; display: flex; align-items: center; justify-content: center; font-size: 18px;">
                <i class="fa-solid fa-triangle-exclamation"></i>
            </div>
        </div>
        <div style="font-size: 12px; color: #64748B;">
            <strong><?= $lateAlertsCount ?></strong> high late | <strong><?= $zeroTenderCount ?></strong> zero tender staff
        </div>
    </div>

</div>

<!-- Section Navigation Tabs -->
<div class="no-print module-tabs report-tabs" style="display: flex; gap: 12px; margin-bottom: 24px; border-bottom: 2px solid #E2E8F0; padding-bottom: 12px; flex-wrap: wrap; width: 100%;">
    <button onclick="switchReportTab('consolidatedTab', this)" class="btn report-tab active" style="border-radius: 12px; padding: 12px 20px; font-weight: 700; font-size: 13px; background: #0F172A; color: #FFF; border: 1px solid #0F172A; cursor: pointer; flex: 1 1 260px; text-align: center; display: inline-flex; align-items: center; justify-content: center; gap: 8px;">
        <i class="fa-solid fa-table-list"></i> Staff Scorecard
    </button>
    <button onclick="switchReportTab('tendersTab', this)" class="btn report-tab" style="border-radius: 12px; padding: 12px 20px; font-weight: 700; font-size: 13px; background: #F8FAFC; color: #475569; border: 1px solid #CBD5E1; cursor: pointer; flex: 1 1 260px; text-align: center; display: inline-flex; align-items: center; justify-content: center; gap: 8px;">
        <i class="fa-solid fa-briefcase"></i> Tender Log <span class="report-tab-count"><?= $totalTendersCount ?></span>
    </button>
</div>

<!-- SECTION 1: CONSOLIDATED STAFF SCORECARD -->
<div id="consolidatedTab" class="report-section">
    <div class="card module-data-card" style="border-radius: 20px; border: 1px solid #E2E8F0; overflow: hidden; background: #FFFFFF; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.03); margin-bottom: 36px;">
        <div class="card-header" style="padding: 20px 24px; border-bottom: 1px solid #F1F5F9; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px; background: #F8FAFC;">
            <div style="flex: 1 1 300px;">
                <h3 style="font-size: 16px; font-weight: 800; color: #0F172A; margin: 0;">Staff Performance</h3>
                <p style="font-size: 12px; color: #64748B; margin: 4px 0 0;">Attendance discipline and tender contribution by staff member.</p>
            </div>
            <span class="badge badge-navy" style="border-radius: 50px; font-weight: 700; padding: 6px 14px; white-space: nowrap;">
                Total: <?= count($users) ?> Personnel
            </span>
        </div>

        <div style="overflow-x: auto;">
            <table class="datatable" style="width: 100%; border-collapse: collapse; text-align: left;">
                <thead>
                    <tr style="background: #F1F5F9; border-bottom: 2px solid #E2E8F0; font-size: 11px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.5px;">
                        <th style="padding: 14px 20px;">Staff Member</th>
                        <th style="padding: 14px 16px;">Department</th>
                        <th style="padding: 14px 16px;">Attendance</th>
                        <th style="padding: 14px 20px; width: 170px;">Discipline</th>
                        <th style="padding: 14px 16px; text-align: center;">Tenders</th>
                        <th style="padding: 14px 20px; text-align: right;">Tender Value</th>
                        <th style="padding: 14px 20px; text-align: center;" class="no-print">Details</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($users)): ?>
                        <tr>
                            <td colspan="7" style="padding: 40px; text-align: center; color: #64748B;">No personnel found for the selected filter criteria.</td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($users as $u): 
                            $uid = $u['id'];
                            $att = $attendanceByUser[$uid] ?? ['total_days_worked' => 0, 'present_on_time' => 0, 'late' => 0, 'leave_mc_absent' => 0, 'records' => []];
                            $tnd = $tendersByUser[$uid] ?? ['count' => 0, 'total_value' => 0.0, 'tenders' => []];

                            $totLogged = $att['present_on_time'] + $att['late'] + $att['leave_mc_absent'];
                            $rate = $totLogged > 0 ? round(($att['present_on_time'] / $totLogged) * 100, 1) : 0;
                            
                            $rateColor = '#059669';
                            $rateBg = '#ECFDF5';
                            if ($totLogged === 0) {
                                $rateColor = '#64748B';
                                $rateBg = '#F1F5F9';
                            } elseif ($rate < 80 || $att['late'] >= 3) {
                                $rateColor = '#DC2626';
                                $rateBg = '#FEF2F2';
                            } elseif ($rate < 90) {
                                $rateColor = '#D97706';
                                $rateBg = '#FFFBEB';
                            }

                            // Encode data for detail modal
                            $modalData = htmlspecialchars(json_encode([
                                'id'         => $u['id'],
                                'name'       => $u['name'],
                                'employee_id'=> $u['employee_id'] ?: 'TBBA-'.str_pad($u['id'], 4, '0', STR_PAD_LEFT),
                                'role'       => strtoupper($u['role']),
                                'position'   => $u['position'] ?: 'Staff Member',
                                'department' => $deptMap[$u['department_id'] ?? 0] ?? 'General',
                                'att_rate'   => $totLogged > 0 ? $rate . '%' : 'No Logs',
                                'present'    => $att['present_on_time'],
                                'late'       => $att['late'],
                                'leave'      => $att['leave_mc_absent'],
                                'att_logs'   => $att['records'] ?? [],
                                'tenders'    => $tnd['tenders'] ?? []
                            ]), ENT_QUOTES, 'UTF-8');
                        ?>
                            <tr style="border-bottom: 1px solid #F1F5F9; transition: background 0.15s ease;" class="report-row">
                                <td style="padding: 16px 20px;">
                                    <div style="display: flex; align-items: center; gap: 12px;">
                                        <div style="width: 38px; height: 38px; border-radius: 50%; background: #E2E8F0; color: #334155; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 700; flex-shrink: 0;">
                                            <?= htmlspecialchars(strtoupper(substr($u['name'], 0, 2)), ENT_QUOTES, 'UTF-8') ?>
                                        </div>
                                        <div>
                                            <div style="font-size: 13px; font-weight: 700; color: #0F172A;">
                                                <?= htmlspecialchars($u['name']) ?>
                                            </div>
                                            <div style="font-size: 11px; color: #64748B;">
                                                <?= htmlspecialchars($u['employee_id'] ?: 'TBBA-'.str_pad($u['id'], 4, '0', STR_PAD_LEFT)) ?> | 
                                                <span style="color: #2563EB; font-weight: 600;"><?= strtoupper($u['role']) ?></span>
                                            </div>
                                        </div>
                                    </div>
                                </td>

                                <td style="padding: 16px 16px; font-size: 13px; color: #334155;">
                                    <?= htmlspecialchars($deptMap[$u['department_id'] ?? 0] ?? '-') ?>
                                </td>

                                <td style="padding: 16px;">
                                    <div class="report-attendance-breakdown">
                                        <span class="present"><strong><?= $att['present_on_time'] ?></strong> Present</span>
                                        <span class="late"><strong><?= $att['late'] ?></strong> Late</span>
                                        <span class="leave"><strong><?= $att['leave_mc_absent'] ?></strong> Leave</span>
                                    </div>
                                </td>

                                <td style="padding: 16px 20px;">
                                    <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 4px;">
                                        <span style="font-size: 12px; font-weight: 700; color: <?= $rateColor ?>;">
                                            <?= $totLogged > 0 ? $rate . '%' : 'N/A' ?>
                                        </span>
                                        <span style="font-size: 10px; color: #94A3B8;"><?= $totLogged ?> log(s)</span>
                                    </div>
                                    <div style="width: 100%; background: #E2E8F0; height: 6px; border-radius: 10px; overflow: hidden;">
                                        <div style="background: <?= $rateColor ?>; height: 100%; width: <?= $totLogged > 0 ? $rate : 0 ?>%; transition: width 0.3s ease;"></div>
                                    </div>
                                </td>

                                <td style="padding: 16px 16px; text-align: center;">
                                    <?php if ($tnd['count'] > 0): ?>
                                        <span style="font-size: 12px; font-weight: 700; background: #EFF6FF; color: #2563EB; padding: 4px 12px; border-radius: 50px; border: 1px solid #BFDBFE;">
                                            <?= $tnd['count'] ?>
                                        </span>
                                    <?php else: ?>
                                        <span style="font-size: 13px; color: #94A3B8;">0</span>
                                    <?php endif; ?>
                                </td>

                                <td style="padding: 16px 20px; text-align: right; font-size: 13px; font-weight: 700; color: #0F172A;">
                                    RM <?= number_format($tnd['total_value'], 2) ?>
                                </td>

                                <td style="padding: 16px 20px; text-align: center;" class="no-print">
                                    <button onclick="openStaffReportModal(this)" data-info="<?= $modalData ?>" 
                                            class="btn" style="background: #EEF2FF; color: #4F46E5; border: 1px solid #C7D2FE; border-radius: 8px; padding: 6px 14px; font-size: 12px; font-weight: 600; cursor: pointer;">
                                        <i class="fa-solid fa-eye"></i> View Logs
                                    </button>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- SECTION 2: DETAILED TENDER & PROJECT SUBMISSION LOG -->
<div id="tendersTab" class="report-section" style="display: none;">
    <div class="card module-data-card" style="border-radius: 20px; border: 1px solid #E2E8F0; overflow: hidden; background: #FFFFFF; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.03); margin-bottom: 36px;">
        <div class="card-header" style="padding: 20px 24px; border-bottom: 1px solid #F1F5F9; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px; background: #F8FAFC;">
            <div style="flex: 1 1 300px;">
                <h3 style="font-size: 16px; font-weight: 800; color: #0F172A; margin: 0;">Tender Details</h3>
                <p style="font-size: 12px; color: #64748B; margin: 4px 0 0;">Tender activity for <?= date('F Y', mktime(0, 0, 0, $selectedMonth, 1, $selectedYear)) ?>.</p>
            </div>
            <span class="badge badge-purple" style="border-radius: 50px; font-weight: 700; padding: 6px 14px; white-space: nowrap;">
                Total Revenue Pool: RM <?= number_format($totalTendersValue, 2) ?>
            </span>
        </div>

        <div style="overflow-x: auto;">
            <table class="datatable" style="width: 100%; border-collapse: collapse; text-align: left;">
                <thead>
                    <tr style="background: #F1F5F9; border-bottom: 2px solid #E2E8F0; font-size: 11px; font-weight: 700; color: #475569; text-transform: uppercase; letter-spacing: 0.5px;">
                        <th style="padding: 14px 20px; width: 120px;">Tender ID</th>
                        <th style="padding: 14px 20px;">Staff In Charge</th>
                        <th style="padding: 14px 20px;">Project & Client Name</th>
                        <th style="padding: 14px 20px; text-align: center;">Closing Date</th>
                        <th style="padding: 14px 20px; text-align: right;">Project Value (RM)</th>
                        <th style="padding: 14px 20px; text-align: right;">Margin (RM)</th>
                        <th style="padding: 14px 20px; text-align: center;">Current Status</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (empty($tenderRows)): ?>
                        <tr>
                            <td colspan="7" style="padding: 40px; text-align: center; color: #64748B;">No tenders or project proposals recorded for this reporting period.</td>
                        </tr>
                    <?php else: ?>
                        <?php foreach ($tenderRows as $tRow):
                            $statusBadge = 'background: #F1F5F9; color: #475569; border: 1px solid #CBD5E1;';
                            if ($tRow['status'] === 'won' || $tRow['status'] === 'approved') {
                                $statusBadge = 'background: #ECFDF5; color: #059669; border: 1px solid #A7F3D0; font-weight: 700;';
                            } elseif ($tRow['status'] === 'submitted' || $tRow['status'] === 'in_progress') {
                                $statusBadge = 'background: #EFF6FF; color: #2563EB; border: 1px solid #BFDBFE; font-weight: 700;';
                            } elseif ($tRow['status'] === 'lost' || $tRow['status'] === 'rejected') {
                                $statusBadge = 'background: #FEF2F2; color: #DC2626; border: 1px solid #FECACA; font-weight: 700;';
                            }
                            $isWon = in_array($tRow['status'], ['won', 'approved']);
                            $rowSelling = $tRow['selling_price'] !== null ? (float)$tRow['selling_price'] : null;
                            $rowCost    = $tRow['cost'] !== null ? (float)$tRow['cost'] : null;
                            $hasMargin  = ($rowSelling !== null && $rowCost !== null);
                            $rowMargin  = $hasMargin ? $rowSelling - $rowCost : null;
                        ?>
                            <tr style="border-bottom: 1px solid #F1F5F9; transition: background 0.15s ease;<?= $isWon ? 'background:#F0FDF4;' : '' ?>" class="report-row">
                                <td style="padding: 16px 20px; font-weight: 700; color: #0F172A; font-family: monospace; font-size: 13px;">
                                    TND-<?= str_pad($tRow['id'], 4, '0', STR_PAD_LEFT) ?>
                                </td>

                                <td style="padding: 16px 20px;">
                                    <div style="font-weight: 700; color: #0F172A; font-size: 13px;"><?= htmlspecialchars($tRow['staff_name'] ?? 'Unknown Staff') ?></div>
                                    <div style="font-size: 11px; color: #64748B;"><?= htmlspecialchars($tRow['position'] ?? 'Staff Member') ?></div>
                                </td>

                                <td style="padding: 16px 20px;">
                                    <div style="font-weight: 700; color: #1E293B; font-size: 13px;"><?= htmlspecialchars($tRow['project_name']) ?></div>
                                    <div style="font-size: 11px; color: #64748B;"><i class="fa-solid fa-building"></i> <?= htmlspecialchars($tRow['client_name']) ?></div>
                                </td>

                                <td style="padding: 16px 20px; text-align: center; font-size: 13px; color: #334155;">
                                    <?= date('d M Y', strtotime($tRow['closing_date'])) ?>
                                </td>

                                <td style="padding: 16px 20px; text-align: right; font-weight: 800; font-size: 13px; color: #0F172A;">
                                    RM <?= number_format((float)($tRow['project_value'] ?? 0), 2) ?>
                                </td>

                                <td style="padding: 16px 20px; text-align: right; font-weight: 700; font-size: 13px;">
                                    <?php if ($hasMargin): ?>
                                        <span style="color: <?= $rowMargin >= 0 ? '#059669' : '#DC2626' ?>;">
                                            <?= $rowMargin >= 0 ? '' : '-' ?>RM <?= number_format(abs($rowMargin), 2) ?>
                                        </span>
                                    <?php else: ?>
                                        <span style="color: #94A3B8; font-weight: 400; font-style: italic;">—</span>
                                    <?php endif; ?>
                                </td>

                                <?php
                                    $sRaw = strtolower(trim($tRow['status'] ?? ''));
                                    if ($sRaw === 'in_progress') $sFmt = 'IN PROGRESS';
                                    else $sFmt = strtoupper(str_replace('_', ' ', $sRaw));
                                ?>
                                <td style="padding: 16px 20px; text-align: center;">
                                    <span style="padding: 4px 12px; border-radius: 50px; font-size: 11px; text-transform: uppercase; <?= $statusBadge ?>">
                                        <?= htmlspecialchars($sFmt) ?>
                                    </span>
                                </td>
                            </tr>
                        <?php endforeach; ?>
                    <?php endif; ?>
                </tbody>
                <?php if ($totalWonCount > 0): ?>
                <tfoot>
                    <tr style="background: #D1FAE5; border-top: 2px solid #6EE7B7;">
                        <td colspan="4" style="padding: 12px 20px; font-weight: 800; font-size: 12px; color: #065F46; text-align: right; text-transform: uppercase; letter-spacing: 0.5px;">
                            <i class="fa-solid fa-trophy" style="margin-right:6px;"></i>Won Tenders Total (<?= $totalWonCount ?> tender<?= $totalWonCount > 1 ? 's' : '' ?>)
                        </td>
                        <td style="padding: 12px 20px; text-align: right; font-weight: 800; font-size: 13px; color: #065F46;">
                            RM <?= number_format($totalWonRevenue, 2) ?>
                        </td>
                        <td style="padding: 12px 20px; text-align: right; font-weight: 800; font-size: 13px; color: <?= $totalWonMargin >= 0 ? '#059669' : '#DC2626' ?>;">
                            <?= $totalWonMargin >= 0 ? '' : '-' ?>RM <?= number_format(abs($totalWonMargin), 2) ?>
                        </td>
                        <td style="padding: 12px 20px; text-align: center;">
                            <span style="padding: 4px 12px; border-radius: 50px; font-size: 11px; font-weight: 800; background:#059669; color:#fff;">COMPANY PROFIT</span>
                        </td>
                    </tr>
                </tfoot>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>

<!-- Print Signature Block (Only shown during printing) -->
<div class="print-signature" style="display: none; margin-top: 50px; padding-top: 20px; border-top: 1px solid #CBD5E1; page-break-inside: avoid;">
    <div style="display: flex; justify-content: space-between;">
        <div style="width: 45%;">
            <p style="font-size: 12px; font-weight: 700; color: #334155; margin-bottom: 50px;">Prepared & Verified By:</p>
            <div style="border-bottom: 1px solid #0F172A; width: 80%; margin-bottom: 6px;"></div>
            <p style="font-size: 12px; font-weight: 700; color: #0F172A; margin: 0;"><?= htmlspecialchars($currentUser['name']) ?></p>
            <p style="font-size: 11px; color: #64748B; margin: 0;">Super Administrator / HR Management</p>
            <p style="font-size: 11px; color: #64748B; margin: 0;">Date: <?= date('d M Y') ?></p>
        </div>

        <div style="width: 45%;">
            <p style="font-size: 12px; font-weight: 700; color: #334155; margin-bottom: 50px;">Approved By Executive Management:</p>
            <div style="border-bottom: 1px solid #0F172A; width: 80%; margin-bottom: 6px;"></div>
            <p style="font-size: 12px; font-weight: 700; color: #0F172A; margin: 0;">Managing Director / Chief Executive Officer</p>
            <p style="font-size: 11px; color: #64748B; margin: 0;">The Bridge Business Alliance (TBBA)</p>
            <p style="font-size: 11px; color: #64748B; margin: 0;">Date: _______________________</p>
        </div>
    </div>
</div>

<!-- Staff Detail Modal -->
<div id="staffReportModal" class="modal module-clean-modal" style="display: none; position: fixed; inset: 0; background: rgba(15,23,42,0.65); z-index: 9999; align-items: center; justify-content: center; backdrop-filter: blur(4px);">
    <div class="modal-content card" style="background: #FFFFFF; border-radius: 20px; width: 90%; max-width: 820px; max-height: 88vh; overflow-y: auto; padding: 28px; box-shadow: 0 20px 40px rgba(0,0,0,0.3); position: relative;">
        <button onclick="closeStaffReportModal()" style="position: absolute; right: 22px; top: 22px; background: #F1F5F9; border: none; width: 34px; height: 34px; border-radius: 50%; font-size: 16px; color: #64748B; cursor: pointer; display: flex; align-items: center; justify-content: center;">
            <i class="fa-solid fa-xmark"></i>
        </button>

        <div style="display: flex; align-items: center; gap: 14px; margin-bottom: 20px; padding-bottom: 16px; border-bottom: 1px solid #E2E8F0;">
            <div id="modalAvatar" style="width: 50px; height: 50px; border-radius: 50%; background: #EFF6FF; color: #2563EB; display: flex; align-items: center; justify-content: center; font-size: 18px; font-weight: 800;">
                ST
            </div>
            <div>
                <h3 id="modalStaffName" style="font-size: 20px; font-weight: 800; color: #0F172A; margin: 0;">Staff Name</h3>
                <p id="modalStaffMeta" style="font-size: 13px; color: #64748B; margin: 2px 0 0;">Role & Department</p>
            </div>
        </div>

        <div class="grid grid-cols-4" style="gap: 12px; margin-bottom: 24px;">
            <div style="background: #ECFDF5; border: 1px solid #A7F3D0; padding: 12px; border-radius: 12px; text-align: center;">
                <div style="font-size: 11px; font-weight: 700; color: #065F46; text-transform: uppercase;">Present / On-Time</div>
                <div id="modalPresent" style="font-size: 20px; font-weight: 800; color: #059669; margin-top: 2px;">0</div>
            </div>
            <div style="background: #FEF2F2; border: 1px solid #FECACA; padding: 12px; border-radius: 12px; text-align: center;">
                <div style="font-size: 11px; font-weight: 700; color: #991B1B; text-transform: uppercase;">Late Days</div>
                <div id="modalLate" style="font-size: 20px; font-weight: 800; color: #DC2626; margin-top: 2px;">0</div>
            </div>
            <div style="background: #F1F5F9; border: 1px solid #CBD5E1; padding: 12px; border-radius: 12px; text-align: center;">
                <div style="font-size: 11px; font-weight: 700; color: #334155; text-transform: uppercase;">Leave / MC</div>
                <div id="modalLeave" style="font-size: 20px; font-weight: 800; color: #475569; margin-top: 2px;">0</div>
            </div>
            <div style="background: #EFF6FF; border: 1px solid #BFDBFE; padding: 12px; border-radius: 12px; text-align: center;">
                <div style="font-size: 11px; font-weight: 700; color: #1E40AF; text-transform: uppercase;">Discipline Rate</div>
                <div id="modalRate" style="font-size: 20px; font-weight: 800; color: #2563EB; margin-top: 2px;">0%</div>
            </div>
        </div>

        <!-- Attendance Logs Table -->
        <h4 style="font-size: 14px; font-weight: 800; color: #0F172A; margin: 0 0 12px; display: flex; align-items: center; gap: 8px;">
            <i class="fa-solid fa-clock" style="color: #2563EB;"></i> Daily Attendance Log (`<?= date('F Y', mktime(0, 0, 0, $selectedMonth, 1, $selectedYear)) ?>`)
        </h4>
        <div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px; max-height: 220px; overflow-y: auto; margin-bottom: 24px; padding: 4px;">
            <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
                <thead>
                    <tr style="background: #E2E8F0; color: #475569; font-weight: 700; text-align: left;">
                        <th style="padding: 8px 12px;">Date</th>
                        <th style="padding: 8px 12px;">Clock In</th>
                        <th style="padding: 8px 12px;">Clock Out</th>
                        <th style="padding: 8px 12px;">Status</th>
                        <th style="padding: 8px 12px;">Reason / Note</th>
                    </tr>
                </thead>
                <tbody id="modalAttTbody">
                </tbody>
            </table>
        </div>

        <!-- Tenders Table -->
        <h4 style="font-size: 14px; font-weight: 800; color: #0F172A; margin: 0 0 12px; display: flex; align-items: center; gap: 8px;">
            <i class="fa-solid fa-briefcase" style="color: #7C3AED;"></i> Assigned Tenders & Project Submissions
        </h4>
        <div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 12px; max-height: 200px; overflow-y: auto; padding: 4px;">
            <table style="width: 100%; border-collapse: collapse; font-size: 12px;">
                <thead>
                    <tr style="background: #E2E8F0; color: #475569; font-weight: 700; text-align: left;">
                        <th style="padding: 8px 12px;">Project Name</th>
                        <th style="padding: 8px 12px;">Client</th>
                        <th style="padding: 8px 12px;">Closing Date</th>
                        <th style="padding: 8px 12px; text-align: right;">Value (RM)</th>
                        <th style="padding: 8px 12px; text-align: center;">Status</th>
                    </tr>
                </thead>
                <tbody id="modalTenderTbody">
                </tbody>
            </table>
        </div>
    </div>
</div>

<style>
.report-overview {
    display: block !important;
    padding: 0 !important;
    overflow: hidden !important;
}
.report-overview-main {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 20px;
    padding: 20px 22px;
}
.report-overview-main > div:first-child { min-width: 0 !important; }
.report-overview-main h1 { display: flex; align-items: center; gap: 10px; }
.report-overview-main h1 > i { color: #2563EB; font-size: 18px; }
.report-export-actions { flex-wrap: nowrap !important; gap: 8px !important; }
.report-export-actions .btn {
    min-width: 72px;
    justify-content: center;
    padding-inline: 13px !important;
}
.report-export-actions .btn:last-child {
    border: 1px solid #CBD5E1 !important;
    background: #F8FAFC !important;
    color: #334155 !important;
}
.report-filterbar {
    padding: 14px 22px 16px;
    border-top: 1px solid #E2E8F0;
    background: #F8FAFC;
}
.report-filter-form { gap: 12px !important; }
.report-filter-fields { gap: 10px !important; }
.report-filter-fields > div { flex: 0 1 auto; }
.report-filter-fields label { margin-bottom: 4px !important; font-size: 9px !important; letter-spacing: .45px; }
.report-filter-fields select { min-height: 38px; background: #FFFFFF !important; }
.report-filter-actions { align-items: flex-end; }
.report-filter-actions .btn { min-height: 38px; white-space: nowrap; }
.executive-summary {
    display: grid;
    grid-template-columns: repeat(4, minmax(0, 1fr));
    gap: 12px !important;
    margin-bottom: 16px !important;
}
.executive-summary .module-stat-card { min-height: 122px !important; }
.report-money { overflow-wrap: anywhere; }
.report-profit-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 10px;
    padding-top: 9px;
    border-top: 1px solid #E2E8F0;
    color: #475569;
    font-size: 10px;
    font-weight: 700;
}
.report-profit-row span { display: inline-flex; align-items: center; gap: 5px; }
.report-attendance-breakdown {
    display: flex;
    align-items: center;
    gap: 5px;
    flex-wrap: wrap;
}
.report-attendance-breakdown > span {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    padding: 4px 7px;
    border-radius: 7px;
    background: #F1F5F9;
    color: #475569;
    font-size: 9px;
    white-space: nowrap;
}
.report-attendance-breakdown .present { background: #ECFDF5; color: #047857; }
.report-attendance-breakdown .late { background: #FEF2F2; color: #B91C1C; }
.report-attendance-breakdown .leave { background: #FFF7ED; color: #C2410C; }
.report-tabs {
    width: fit-content !important;
    gap: 4px !important;
    margin-bottom: 12px !important;
    padding: 4px !important;
    border: 1px solid #E2E8F0 !important;
    border-radius: 10px;
    background: #F1F5F9;
}
.report-tabs .report-tab {
    flex: none !important;
    min-height: 36px;
    padding: 8px 13px !important;
    border-radius: 7px !important;
    font-size: 11px !important;
}
.report-tab-count {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 19px;
    height: 19px;
    padding: 0 5px;
    border-radius: 999px;
    background: #E2E8F0;
    color: #475569;
    font-size: 9px;
}
.report-section .card-header {
    padding: 16px 18px !important;
    background: #FFFFFF !important;
}
.report-section .dataTables_length { display: none !important; }
.report-section .dt-top-bar { justify-content: flex-end !important; }
.report-section .dataTables_filter { width: min(320px, 100%); }
.report-section .dataTables_filter input { width: 100% !important; }
.report-row:hover {
    background: #F8FAFC !important;
}
@media (max-width: 1100px) {
    .executive-summary { grid-template-columns: repeat(2, minmax(0, 1fr)); }
    .report-filter-form { align-items: flex-end !important; }
    .report-filter-actions { width: 100%; justify-content: flex-end; }
}
@media (max-width: 720px) {
    .report-overview-main { align-items: flex-start; flex-direction: column; padding: 16px; }
    .report-overview-main h1 { font-size: 18px !important; }
    .report-export-actions { width: 100%; }
    .report-export-actions .btn { flex: 1; min-width: 0; }
    .report-filterbar { padding: 14px 16px 16px; }
    .report-filter-fields { display: grid !important; grid-template-columns: 1fr 1fr; width: 100%; }
    .report-filter-fields > div:last-child { grid-column: 1 / -1; }
    .report-filter-fields select { width: 100%; min-width: 0 !important; }
    .report-filter-actions { display: grid !important; grid-template-columns: 1fr 1fr; width: 100%; }
    .report-filter-actions .btn { justify-content: center; }
    .report-tabs { display: grid !important; grid-template-columns: 1fr 1fr; width: 100% !important; }
    .report-tabs .report-tab { justify-content: center; white-space: nowrap; }
}
@media (max-width: 520px) {
    .executive-summary { grid-template-columns: 1fr; }
    .executive-summary .module-stat-card { min-height: 0 !important; }
}
@media print {
    .no-print, .sidebar, .navbar, .sidebar-toggle, .btn, .print-header + .card {
        display: none !important;
    }
    .print-header, .print-signature {
        display: block !important;
    }
    .report-section {
        display: block !important;
        margin-bottom: 30px !important;
    }
    .card {
        border: 1px solid #CBD5E1 !important;
        box-shadow: none !important;
    }
    body, .main-content, .content-wrapper {
        margin: 0 !important;
        padding: 0 !important;
        background: #FFF !important;
        width: 100% !important;
    }
}
</style>

<script>
function switchReportTab(tabId, btn) {
    document.querySelectorAll('.report-section').forEach(s => s.style.display = 'none');
    document.getElementById(tabId).style.display = 'block';
    
    document.querySelectorAll('.report-tab').forEach(b => {
        b.style.background = '#F8FAFC';
        b.style.color = '#475569';
        b.style.border = '1px solid #CBD5E1';
    });
    btn.style.background = '#0F172A';
    btn.style.color = '#FFF';
    btn.style.border = '1px solid #0F172A';
}

function openStaffReportModal(btn) {
    const data = JSON.parse(btn.getAttribute('data-info'));
    document.getElementById('modalAvatar').innerText = data.name.substring(0, 2).toUpperCase();
    document.getElementById('modalStaffName').innerText = data.name;
    document.getElementById('modalStaffMeta').innerText = `${data.employee_id} | ${data.role} (${data.department})`;
    
    document.getElementById('modalPresent').innerText = data.present;
    document.getElementById('modalLate').innerText = data.late;
    document.getElementById('modalLeave').innerText = data.leave;
    document.getElementById('modalRate').innerText = data.att_rate;

    // Populate Attendance Logs Table
    const attTbody = document.getElementById('modalAttTbody');
    attTbody.innerHTML = '';
    if (data.att_logs.length === 0) {
        attTbody.innerHTML = '<tr><td colspan="5" style="padding: 16px; text-align: center; color: #64748B;">No daily attendance records found for this month.</td></tr>';
    } else {
        data.att_logs.forEach(row => {
            let stColor = '#059669';
            if (row.status.toLowerCase() === 'late') stColor = '#DC2626';
            else if (['mc', 'leave', 'absent'].includes(row.status.toLowerCase())) stColor = '#D97706';
            
            attTbody.innerHTML += `
                <tr style="border-bottom: 1px solid #F1F5F9;">
                    <td style="padding: 8px 12px; font-weight: 600;">${escapeReportHtml(row.date)}</td>
                    <td style="padding: 8px 12px;">${escapeReportHtml(row.clock_in ? row.clock_in.split(' ')[1] : '-')}</td>
                    <td style="padding: 8px 12px;">${escapeReportHtml(row.clock_out ? row.clock_out.split(' ')[1] : '-')}</td>
                    <td style="padding: 8px 12px; font-weight: 700; color: ${stColor}; text-transform: capitalize;">${escapeReportHtml(row.status)}</td>
                    <td style="padding: 8px 12px; color: #475569;">${escapeReportHtml(row.reason || row.clock_out_reason || '-')}</td>
                </tr>
            `;
        });
    }

    // Populate Tenders Table
    const tndTbody = document.getElementById('modalTenderTbody');
    tndTbody.innerHTML = '';
    if (data.tenders.length === 0) {
        tndTbody.innerHTML = '<tr><td colspan="5" style="padding: 16px; text-align: center; color: #64748B;">No assigned tenders or project proposals recorded for this month.</td></tr>';
    } else {
        data.tenders.forEach(t => {
            let badgeStyle = 'background: #F1F5F9; color: #475569;';
            if (t.status === 'won' || t.status === 'approved') badgeStyle = 'background: #ECFDF5; color: #059669; font-weight: 700;';
            else if (t.status === 'submitted' || t.status === 'in_progress') badgeStyle = 'background: #EFF6FF; color: #2563EB; font-weight: 700;';
            else if (t.status === 'lost') badgeStyle = 'background: #FEF2F2; color: #DC2626; font-weight: 700;';

            tndTbody.innerHTML += `
                <tr style="border-bottom: 1px solid #F1F5F9;">
                    <td style="padding: 8px 12px; font-weight: 700; color: #0F172A;">${escapeReportHtml(t.project_name)}</td>
                    <td style="padding: 8px 12px; color: #475569;">${escapeReportHtml(t.client_name)}</td>
                    <td style="padding: 8px 12px;">${escapeReportHtml(t.closing_date)}</td>
                    <td style="padding: 8px 12px; text-align: right; font-weight: 700;">RM ${parseFloat(t.project_value || 0).toLocaleString('en-MY', {minimumFractionDigits: 2})}</td>
                    <td style="padding: 8px 12px; text-align: center;"><span style="padding: 2px 8px; border-radius: 50px; font-size: 11px; text-transform: uppercase; ${badgeStyle}">${escapeReportHtml(t.status)}</span></td>
                </tr>
            `;
        });
    }

    document.getElementById('staffReportModal').style.display = 'flex';
}

function escapeReportHtml(value) {
    return String(value ?? '').replace(/[&<>"']/g, character => ({
        '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;'
    })[character]);
}

function closeStaffReportModal() {
    document.getElementById('staffReportModal').style.display = 'none';
}
</script>

<?php include __DIR__ . '/../layouts/footer.php'; ?>
