<?php $isReceipt = ($payment['direction'] ?? '') === 'in'; ?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title><?= htmlspecialchars($payment['payment_no']) ?> | TBBA</title>
<style>body{margin:0;padding:35px;background:#f1f5f9;color:#0f172a;font-family:Arial,sans-serif}.sheet{max-width:780px;margin:auto;padding:42px;background:#fff;border:1px solid #cbd5e1;box-shadow:0 12px 35px rgba(15,23,42,.1)}.head{display:flex;justify-content:space-between;gap:20px;border-bottom:3px solid #0f766e;padding-bottom:22px}.head h1{margin:0;font-size:27px}.head p{margin:6px 0 0;color:#64748b}.doc{text-align:right}.doc strong{display:block;color:#0f766e;font-size:20px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:26px 0}.box{padding:15px;border:1px solid #e2e8f0;border-radius:10px}.box small{display:block;color:#64748b;font-size:10px;font-weight:bold;text-transform:uppercase}.box strong{display:block;margin-top:5px}.amount{margin:28px 0;padding:25px;text-align:center;border-radius:12px;background:#ecfdf5;color:#065f46}.amount small{display:block;font-size:11px;font-weight:bold;text-transform:uppercase}.amount strong{display:block;margin-top:8px;font-size:31px}.footer{display:flex;justify-content:space-between;gap:20px;margin-top:45px;padding-top:16px;border-top:1px solid #e2e8f0;color:#64748b;font-size:11px}.print{display:block;margin:18px auto;padding:10px 16px;border:0;border-radius:8px;background:#0f766e;color:white;font-weight:bold;cursor:pointer}@media print{body{padding:0;background:#fff}.sheet{border:0;box-shadow:none}.print{display:none}}@media(max-width:600px){body{padding:10px}.sheet{padding:22px}.head,.grid{grid-template-columns:1fr;display:grid}.doc{text-align:left}}</style></head><body>
<main class="sheet"><div class="head"><div><h1>The Bridge Business Alliance</h1><p>TBBA Corporate Finance</p></div><div class="doc"><strong><?= $isReceipt?'Official Receipt':'Payment Voucher' ?></strong><span><?= htmlspecialchars($payment['payment_no']) ?></span></div></div>
<div class="grid"><div class="box"><small><?= $isReceipt?'Received From':'Paid To' ?></small><strong><?= htmlspecialchars($payment['party_name']) ?></strong></div><div class="box"><small>Payment Date</small><strong><?= date('d M Y',strtotime($payment['payment_date'])) ?></strong></div><div class="box"><small>For Document</small><strong><?= htmlspecialchars($payment['document_reference']) ?></strong><span><?= htmlspecialchars($payment['title']) ?></span></div><div class="box"><small>Payment Method</small><strong><?= htmlspecialchars(ucwords(str_replace('_',' ',$payment['method']))) ?></strong><span><?= htmlspecialchars($payment['bank_reference']?:'No bank reference') ?></span></div></div>
<div class="amount"><small><?= $isReceipt?'Amount Received':'Amount Paid' ?></small><strong>RM <?= number_format((float)$payment['amount'],2) ?></strong></div>
<div class="grid"><div class="box"><small>Recorded By</small><strong><?= htmlspecialchars($payment['created_by_name']?:'TBBA Finance') ?></strong></div><div class="box"><small>Remaining Document Balance</small><strong>RM <?= number_format((float)$payment['balance_due'],2) ?></strong></div></div>
<div class="footer"><span>Generated <?= date('d M Y, h:i A') ?></span><span>This computer-generated document is traceable in the TBBA Finance Control Center.</span></div></main><button class="print" onclick="window.print()">Print / Save PDF</button>
</body></html>
