<?php
/**
 * Consolidated Executive Monthly Report Controller
 * Company: The Bridge Business Alliance (TBBA)
 * Module: Executive Consolidated Reporting (GPS Attendance + Tender KPI Tracker by Month)
 */

require_once __DIR__ . '/../core/Auth.php';
require_once __DIR__ . '/../core/Helper.php';
require_once __DIR__ . '/../models/User.php';
require_once __DIR__ . '/../models/Attendance.php';
require_once __DIR__ . '/../models/Tender.php';
require_once __DIR__ . '/../models/Department.php';
require_once __DIR__ . '/../core/fpdf.php';

class TBBA_ReportPDF extends FPDF {
    public $reportPeriod = '';
    public $superAdminName = '';

    function Header() {
        // Corporate Header
        $this->SetFont('helvetica', 'B', 15);
        $this->SetTextColor(15, 23, 42); // Navy
        $this->Cell(0, 8, 'THE BRIDGE BUSINESS ALLIANCE (TBBA)', 0, 1, 'C');
        
        $this->SetFont('helvetica', 'B', 10);
        $this->SetTextColor(37, 99, 235); // Enterprise Blue
        $this->Cell(0, 6, 'EXECUTIVE CONSOLIDATED MONTHLY REPORT (ATTENDANCE & TENDER KPI)', 0, 1, 'C');
        
        $this->SetFont('helvetica', '', 9);
        $this->SetTextColor(100, 116, 139);
        $this->Cell(0, 5, 'Reporting Period: ' . $this->reportPeriod . '  |  Generated By: ' . $this->superAdminName, 0, 1, 'C');
        
        // Line break and separator
        $this->Ln(3);
        $this->SetDrawColor(15, 23, 42);
        $this->SetLineWidth(0.6);
        $this->Line(10, $this->GetY(), $this->GetPageWidth() - 10, $this->GetY());
        $this->Ln(6);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->SetTextColor(100, 116, 139);
        $this->Cell(95, 6, 'TBBA Enterprise ERP - Executive Intelligence', 0, 0, 'L');
        $this->Cell(95, 6, 'Page ' . $this->PageNo() . ' of {nb}', 0, 0, 'R');
    }
}

class ReportController {

    public static function index() {
        Auth::requireLogin();
        
        // Restrict strictly to Super Admin or users with system view permissions
        if (!Auth::isSuperAdmin() && !Auth::hasPermission('system', 'view')) {
            Helper::redirect('index.php?page=dashboard&error=unauthorized_report');
            return;
        }

        // Get filter inputs
        $selectedMonth = isset($_GET['month']) ? (int)$_GET['month'] : (int)date('m');
        if ($selectedMonth < 1 || $selectedMonth > 12) $selectedMonth = (int)date('m');
        
        $selectedYear = isset($_GET['year']) ? (int)$_GET['year'] : (int)date('Y');
        if ($selectedYear < 2020 || $selectedYear > 2035) $selectedYear = (int)date('Y');

        $selectedDept = isset($_GET['department_id']) && $_GET['department_id'] !== '' ? (int)$_GET['department_id'] : null;
        
        $monthYearStr = sprintf('%04d-%02d', $selectedYear, $selectedMonth);

        // Fetch all active staff / users
        $userSql = "SELECT id, name, email, role, position, department_id, employee_id, avatar, status 
                    FROM users 
                    WHERE status = 'active' ";
        $userParams = [];
        if ($selectedDept) {
            $userSql .= " AND department_id = ? ";
            $userParams[] = $selectedDept;
        }
        $userSql .= " ORDER BY name ASC";
        $users = Database::query($userSql, $userParams)->fetchAll();

        // Fetch Department map
        $departments = Department::getAll();
        $deptMap = [];
        foreach ($departments as $d) {
            $deptMap[$d['id']] = $d['name'];
        }

        // Fetch all attendance records for selected month & year
        $attRows = Database::query(
            "SELECT id, user_id, date, status, clock_in, clock_out, reason, clock_out_reason 
             FROM attendance 
             WHERE MONTH(date) = ? AND YEAR(date) = ? 
             ORDER BY date ASC, clock_in ASC",
            [$selectedMonth, $selectedYear]
        )->fetchAll();

        // Group attendance by user_id
        $attendanceByUser = [];
        foreach ($attRows as $row) {
            $uid = $row['user_id'];
            if (!isset($attendanceByUser[$uid])) {
                $attendanceByUser[$uid] = [
                    'total_days_worked' => 0,
                    'present_on_time'   => 0,
                    'late'              => 0,
                    'leave_mc_absent'   => 0,
                    'records'           => []
                ];
            }
            $attendanceByUser[$uid]['records'][] = $row;
            $st = strtolower(trim($row['status']));
            if (in_array($st, ['present', 'on_time', 'on time'])) {
                $attendanceByUser[$uid]['present_on_time']++;
                $attendanceByUser[$uid]['total_days_worked']++;
            } elseif ($st === 'late') {
                $attendanceByUser[$uid]['late']++;
                $attendanceByUser[$uid]['total_days_worked']++;
            } else {
                $attendanceByUser[$uid]['leave_mc_absent']++;
            }
        }

        // Fetch all tenders matching this month/year or closing in this month/year
        $tenderRows = Database::query(
            "SELECT t.*, u.name as staff_name, u.position 
             FROM tenders t 
             LEFT JOIN users u ON t.user_id = u.id 
             WHERE t.month_year = ? OR DATE_FORMAT(t.closing_date, '%Y-%m') = ? OR DATE_FORMAT(t.created_at, '%Y-%m') = ? 
             ORDER BY t.closing_date ASC",
            [$monthYearStr, $monthYearStr, $monthYearStr]
        )->fetchAll();

        // Group tenders by user_id
        $tendersByUser = [];
        foreach ($tenderRows as $tRow) {
            $uid = $tRow['user_id'];
            if (!isset($tendersByUser[$uid])) {
                $tendersByUser[$uid] = [
                    'count'       => 0,
                    'total_value' => 0.0,
                    'tenders'     => []
                ];
            }
            $tendersByUser[$uid]['tenders'][] = $tRow;
            $tendersByUser[$uid]['count']++;
            $tendersByUser[$uid]['total_value'] += (float)($tRow['project_value'] ?? 0);
        }

        // Calculate consolidated executive metrics
        $totalStaffCount = count($users);
        $totalTendersCount = count($tenderRows);
        $totalTendersValue = 0.0;
        $totalWonRevenue   = 0.0;
        $totalWonMargin    = 0.0;
        $totalWonCount     = 0;
        foreach ($tenderRows as $tr) {
            $totalTendersValue += (float)($tr['project_value'] ?? 0);
            $sRawCheck = strtolower(trim($tr['status'] ?? ''));
            if (in_array($sRawCheck, ['won', 'approved'])) {
                $wonSelling = (float)($tr['selling_price'] ?? $tr['project_value'] ?? 0);
                $wonCost    = (float)($tr['cost'] ?? 0);
                $totalWonRevenue += $wonSelling;
                $totalWonMargin  += ($wonSelling - $wonCost);
                $totalWonCount++;
            }
        }

        $totalAttRateSum = 0.0;
        $staffWithAttCount = 0;
        $lateAlertsCount = 0;
        $zeroTenderCount = 0;

        foreach ($users as $u) {
            $uid = $u['id'];
            $att = $attendanceByUser[$uid] ?? ['total_days_worked' => 0, 'present_on_time' => 0, 'late' => 0, 'leave_mc_absent' => 0];
            $tnd = $tendersByUser[$uid] ?? ['count' => 0, 'total_value' => 0.0];

            $totLogged = $att['present_on_time'] + $att['late'] + $att['leave_mc_absent'];
            if ($totLogged > 0) {
                $rate = ($att['present_on_time'] / $totLogged) * 100;
                $totalAttRateSum += $rate;
                $staffWithAttCount++;
            }
            if ($att['late'] >= 3) {
                $lateAlertsCount++;
            }
            if ($tnd['count'] === 0 && !in_array($u['role'], ['super_admin', 'admin', 'hr'])) {
                $zeroTenderCount++;
            }
        }

        $avgAttendanceRate = $staffWithAttCount > 0 ? round($totalAttRateSum / $staffWithAttCount, 1) : 100.0;

        $export = $_GET['export'] ?? '';

        // ── Check if Native PDF Export requested (`export=pdf`) ──
        if ($export === 'pdf') {
            self::exportPdf($selectedMonth, $selectedYear, $users, $attendanceByUser, $tendersByUser, $deptMap, $avgAttendanceRate, $totalTendersValue, $lateAlertsCount, $zeroTenderCount, $tenderRows, $totalWonMargin, $totalWonRevenue, $totalWonCount);
            return;
        }

        // ── Check if Standalone Formal Document View requested (`export=print`) ──
        if ($export === 'print') {
            include __DIR__ . '/../views/reports/print.php';
            return;
        }

        // ── Check if CSV Export requested (`export=csv`) ──
        if ($export === 'csv') {
            self::exportCsv($selectedMonth, $selectedYear, $users, $attendanceByUser, $tendersByUser, $deptMap);
            return;
        }

        $pageTitle = 'Monthly Reports';
        include __DIR__ . '/../views/reports/index.php';
    }

    // Generate and Download Native PDF using FPDF
    private static function exportPdf($month, $year, $users, $attendanceByUser, $tendersByUser, $deptMap, $avgAttendanceRate, $totalTendersValue, $lateAlertsCount, $zeroTenderCount, $tenderRows, $totalWonMargin = 0.0, $totalWonRevenue = 0.0, $totalWonCount = 0) {
        $monthName = date('F', mktime(0, 0, 0, $month, 1, $year));
        $periodStr = "{$monthName} {$year}";
        
        $pdf = new TBBA_ReportPDF('P', 'mm', 'A4');
        $pdf->AliasNbPages();
        $pdf->reportPeriod = $periodStr;
        $pdf->superAdminName = Auth::user()['name'] ?? 'Super Admin';
        $pdf->SetMargins(10, 12, 10);
        $pdf->SetAutoPageBreak(true, 18);
        $pdf->AddPage();

        // ── Summary KPI Box (4 columns across 190mm) ──
        $pdf->SetFont('helvetica', 'B', 8);
        $pdf->SetFillColor(248, 250, 252);
        $pdf->SetDrawColor(203, 213, 225);
        $pdf->SetTextColor(100, 116, 139);
        
        $wCol = 47.5;
        
        // Labels
        $pdf->Cell($wCol, 5, 'PERSONNEL ASSESSED', 1, 0, 'C', true);
        $pdf->Cell($wCol, 5, 'AVG ATTENDANCE RATE', 1, 0, 'C', true);
        $pdf->Cell($wCol, 5, 'MONTHLY TENDER REVENUE', 1, 0, 'C', true);
        $pdf->Cell($wCol, 5, 'DISCIPLINE / KPI ALERTS', 1, 1, 'C', true);
        
        // Values
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->SetTextColor(15, 23, 42);
        $pdf->Cell($wCol, 8, count($users) . ' Personnel', 1, 0, 'C', true);
        
        if ($avgAttendanceRate >= 90) $pdf->SetTextColor(5, 150, 105);
        elseif ($avgAttendanceRate >= 80) $pdf->SetTextColor(217, 119, 6);
        else $pdf->SetTextColor(220, 38, 38);
        $pdf->Cell($wCol, 8, $avgAttendanceRate . '%', 1, 0, 'C', true);
        
        $pdf->SetTextColor(124, 58, 237);
        $pdf->Cell($wCol, 8, 'RM ' . number_format($totalTendersValue, 2), 1, 0, 'C', true);
        
        $pdf->SetTextColor(220, 38, 38);
        $pdf->Cell($wCol, 8, ($lateAlertsCount + $zeroTenderCount) . ' Alert(s)', 1, 1, 'C', true);
        
        $pdf->Ln(6);

        // ── Section 1: Staff Scorecard Table ──
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->SetTextColor(15, 23, 42);
        $pdf->Cell(0, 6, 'SECTION 1: PERSONNEL ATTENDANCE & TENDER KPI SCORECARD', 0, 1, 'L');
        $pdf->Ln(1);

        $pdf->SetFont('helvetica', 'B', 8);
        $pdf->SetFillColor(241, 245, 249);
        $pdf->SetDrawColor(203, 213, 225);
        $pdf->SetTextColor(15, 23, 42);
        
        // Width = 190mm: ID(22), Name(44), Dept(34), Present(16), Late(14), Att%(18), Tenders(16), Value RM(26)
        $pdf->Cell(22, 6, 'Staff ID', 1, 0, 'L', true);
        $pdf->Cell(44, 6, 'Staff Name & Role', 1, 0, 'L', true);
        $pdf->Cell(34, 6, 'Department', 1, 0, 'L', true);
        $pdf->Cell(16, 6, 'Present', 1, 0, 'C', true);
        $pdf->Cell(14, 6, 'Late', 1, 0, 'C', true);
        $pdf->Cell(18, 6, 'Att Rate', 1, 0, 'C', true);
        $pdf->Cell(16, 6, 'Tenders', 1, 0, 'C', true);
        $pdf->Cell(26, 6, 'Total Value (RM)', 1, 1, 'R', true);

        $pdf->SetFont('helvetica', '', 8);
        if (empty($users)) {
            $pdf->Cell(190, 8, 'No personnel found for this reporting period.', 1, 1, 'C');
        } else {
            foreach ($users as $u) {
                $uid = $u['id'];
                $att = $attendanceByUser[$uid] ?? ['total_days_worked' => 0, 'present_on_time' => 0, 'late' => 0, 'leave_mc_absent' => 0];
                $tnd = $tendersByUser[$uid] ?? ['count' => 0, 'total_value' => 0.0];

                $totLogged = $att['present_on_time'] + $att['late'] + $att['leave_mc_absent'];
                $rate = $totLogged > 0 ? round(($att['present_on_time'] / $totLogged) * 100, 1) : 0;
                $rateStr = $totLogged > 0 ? $rate . '%' : 'N/A';

                $empId = substr($u['employee_id'] ?: 'TBBA-'.str_pad($u['id'], 4, '0', STR_PAD_LEFT), 0, 12);
                $nameStr = substr($u['name'], 0, 24);
                $deptStr = substr($deptMap[$u['department_id'] ?? 0] ?? '-', 0, 18);

                if ($pdf->GetY() > 255) {
                    $pdf->AddPage();
                    $pdf->SetFont('helvetica', 'B', 8);
                    $pdf->SetFillColor(241, 245, 249);
                    $pdf->Cell(22, 6, 'Staff ID', 1, 0, 'L', true);
                    $pdf->Cell(44, 6, 'Staff Name & Role', 1, 0, 'L', true);
                    $pdf->Cell(34, 6, 'Department', 1, 0, 'L', true);
                    $pdf->Cell(16, 6, 'Present', 1, 0, 'C', true);
                    $pdf->Cell(14, 6, 'Late', 1, 0, 'C', true);
                    $pdf->Cell(18, 6, 'Att Rate', 1, 0, 'C', true);
                    $pdf->Cell(16, 6, 'Tenders', 1, 0, 'C', true);
                    $pdf->Cell(26, 6, 'Total Value (RM)', 1, 1, 'R', true);
                    $pdf->SetFont('helvetica', '', 8);
                }

                $pdf->SetTextColor(15, 23, 42);
                $pdf->Cell(22, 6, $empId, 1, 0, 'L');
                $pdf->Cell(44, 6, $nameStr, 1, 0, 'L');
                $pdf->Cell(34, 6, $deptStr, 1, 0, 'L');
                
                $pdf->SetTextColor(5, 150, 105);
                $pdf->Cell(16, 6, $att['present_on_time'], 1, 0, 'C');
                
                $pdf->SetTextColor($att['late'] > 0 ? 220 : 100, $att['late'] > 0 ? 38 : 116, $att['late'] > 0 ? 38 : 139);
                $pdf->Cell(14, 6, $att['late'], 1, 0, 'C');
                
                $pdf->SetTextColor($totLogged > 0 && $rate < 80 ? 220 : 15, $totLogged > 0 && $rate < 80 ? 38 : 23, $totLogged > 0 && $rate < 80 ? 38 : 42);
                $pdf->Cell(18, 6, $rateStr, 1, 0, 'C');
                
                $pdf->SetTextColor(37, 99, 235);
                $pdf->Cell(16, 6, $tnd['count'], 1, 0, 'C');
                
                $pdf->SetTextColor(15, 23, 42);
                $pdf->Cell(26, 6, number_format($tnd['total_value'], 2), 1, 1, 'R');
            }
        }

        $pdf->Ln(6);

        // ── Section 2: Detailed Tender Log ──
        if ($pdf->GetY() > 220) {
            $pdf->AddPage();
        }
        $pdf->SetFont('helvetica', 'B', 10);
        $pdf->SetTextColor(15, 23, 42);
        $pdf->Cell(0, 6, 'SECTION 2: DETAILED TENDER & PROJECT SUBMISSION LOG', 0, 1, 'L');
        $pdf->Ln(1);

        $pdf->SetFont('helvetica', 'B', 8);
        $pdf->SetFillColor(241, 245, 249);
        // Total width = 190mm: ID(18), Staff(34), Project(50), Closing(20), Value(22), Margin(22), Status(24)
        $pdf->Cell(18, 6, 'Tender ID', 1, 0, 'L', true);
        $pdf->Cell(34, 6, 'Staff In Charge', 1, 0, 'L', true);
        $pdf->Cell(50, 6, 'Project & Client Name', 1, 0, 'L', true);
        $pdf->Cell(20, 6, 'Closing Date', 1, 0, 'C', true);
        $pdf->Cell(22, 6, 'Project Value (RM)', 1, 0, 'R', true);
        $pdf->Cell(22, 6, 'Margin (RM)', 1, 0, 'R', true);
        $pdf->Cell(24, 6, 'Status', 1, 1, 'C', true);

        $pdf->SetFont('helvetica', '', 8);
        if (empty($tenderRows)) {
            $pdf->Cell(190, 8, 'No tenders or project proposals recorded for this reporting period.', 1, 1, 'C');
        } else {
            foreach ($tenderRows as $tRow) {
                if ($pdf->GetY() > 255) {
                    $pdf->AddPage();
                    $pdf->SetFont('helvetica', 'B', 8);
                    $pdf->SetFillColor(241, 245, 249);
                    $pdf->Cell(18, 6, 'Tender ID', 1, 0, 'L', true);
                    $pdf->Cell(34, 6, 'Staff In Charge', 1, 0, 'L', true);
                    $pdf->Cell(50, 6, 'Project & Client Name', 1, 0, 'L', true);
                    $pdf->Cell(20, 6, 'Closing Date', 1, 0, 'C', true);
                    $pdf->Cell(22, 6, 'Project Value (RM)', 1, 0, 'R', true);
                    $pdf->Cell(22, 6, 'Margin (RM)', 1, 0, 'R', true);
                    $pdf->Cell(24, 6, 'Status', 1, 1, 'C', true);
                    $pdf->SetFont('helvetica', '', 8);
                }

                $tid = 'TND-'.str_pad($tRow['id'], 4, '0', STR_PAD_LEFT);
                $staffStr = substr($tRow['staff_name'] ?? 'Unknown', 0, 18);
                $projStr = substr($tRow['project_name'] . ' (' . $tRow['client_name'] . ')', 0, 30);
                $cDate = date('d M Y', strtotime($tRow['closing_date']));
                $valStr = number_format((float)($tRow['project_value'] ?? 0), 2);

                $statusRaw = strtolower(trim($tRow['status'] ?? ''));
                if ($statusRaw === 'in_progress') $statusStr = 'IN PROGRESS';
                else $statusStr = strtoupper(str_replace('_', ' ', $statusRaw));

                // Margin only meaningful when selling_price & cost are present
                $rowSelling = (float)($tRow['selling_price'] ?? 0);
                $rowCost    = (float)($tRow['cost'] ?? 0);
                $hasMargin  = ($tRow['selling_price'] !== null && $tRow['cost'] !== null);
                $rowMargin  = $rowSelling - $rowCost;
                $marginStr  = $hasMargin ? number_format($rowMargin, 2) : '-';

                $pdf->Cell(18, 6, $tid, 1, 0, 'L');
                $pdf->Cell(34, 6, $staffStr, 1, 0, 'L');
                $pdf->Cell(50, 6, $projStr, 1, 0, 'L');
                $pdf->Cell(20, 6, $cDate, 1, 0, 'C');
                $pdf->Cell(22, 6, $valStr, 1, 0, 'R');

                // Margin cell: green if positive, red if negative
                if ($hasMargin) {
                    if ($rowMargin >= 0) $pdf->SetTextColor(5, 150, 105);
                    else $pdf->SetTextColor(220, 38, 38);
                } else {
                    $pdf->SetTextColor(148, 163, 184);
                }
                $pdf->Cell(22, 6, $marginStr, 1, 0, 'R');
                $pdf->SetTextColor(15, 23, 42);

                if (in_array($statusRaw, ['won', 'approved'])) $pdf->SetTextColor(5, 150, 105);
                elseif (in_array($statusRaw, ['lost', 'rejected'])) $pdf->SetTextColor(220, 38, 38);
                else $pdf->SetTextColor(37, 99, 235);
                $pdf->Cell(24, 6, $statusStr, 1, 1, 'C');
                $pdf->SetTextColor(15, 23, 42);
            }

            // Won tender summary row
            if ($totalWonCount > 0) {
                $pdf->Ln(3);
                $pdf->SetFont('helvetica', 'B', 8);
                $pdf->SetFillColor(236, 253, 245);
                $pdf->SetTextColor(5, 150, 105);
                $pdf->Cell(122, 6, 'WON TENDERS TOTAL (' . $totalWonCount . ' tender' . ($totalWonCount > 1 ? 's' : '') . ')', 1, 0, 'R', true);
                $pdf->Cell(22, 6, number_format($totalWonRevenue, 2), 1, 0, 'R', true);
                $pdf->Cell(22, 6, number_format($totalWonMargin, 2), 1, 0, 'R', true);
                $pdf->Cell(24, 6, '', 1, 1, 'C', true);
                $pdf->SetTextColor(15, 23, 42);
            }
        }

        // ── Section 3: Signatures (Row-by-Row Layout to prevent any overlap) ──
        if ($pdf->GetY() > 230) {
            $pdf->AddPage();
            $ySig = $pdf->GetY() + 4;
        } else {
            $pdf->Ln(12);
            $ySig = $pdf->GetY();
        }
        
        // Row 1: Titles
        $pdf->SetXY(10, $ySig);
        $pdf->SetFont('helvetica', 'B', 8);
        $pdf->SetTextColor(71, 85, 105);
        $pdf->Cell(90, 5, 'Prepared & Verified By:', 0, 0, 'L');
        $pdf->Cell(10, 5, '', 0, 0, 'C');
        $pdf->Cell(90, 5, 'Approved By Executive Management:', 0, 1, 'L');
        
        // Spacing for physical signature
        $pdf->Ln(14);
        $yLine = $pdf->GetY();
        
        // Row 2: Signature Lines
        $pdf->SetDrawColor(15, 23, 42);
        $pdf->Line(10, $yLine, 95, $yLine);
        $pdf->Line(110, $yLine, 195, $yLine);
        $pdf->Ln(2);
        
        // Row 3: Names
        $pdf->SetFont('helvetica', 'B', 9);
        $pdf->SetTextColor(15, 23, 42);
        $pdf->Cell(90, 5, $pdf->superAdminName, 0, 0, 'L');
        $pdf->Cell(10, 5, '', 0, 0, 'C');
        $pdf->Cell(90, 5, 'Managing Director / Chief Executive Officer', 0, 1, 'L');
        
        // Row 4: Roles
        $pdf->SetFont('helvetica', '', 8);
        $pdf->SetTextColor(100, 116, 139);
        $pdf->Cell(90, 4, 'Super Administrator / HR Management', 0, 0, 'L');
        $pdf->Cell(10, 4, '', 0, 0, 'C');
        $pdf->Cell(90, 4, 'The Bridge Business Alliance (TBBA)', 0, 1, 'L');
        
        // Row 5: Dates
        $pdf->Cell(90, 4, 'Date: ' . date('d M Y'), 0, 0, 'L');
        $pdf->Cell(10, 4, '', 0, 0, 'C');
        $pdf->Cell(90, 4, 'Date: ________________________', 0, 1, 'L');

        // Output binary PDF to download
        $pdf->Output('D', "TBBA_Executive_Report_{$monthName}_{$year}.pdf");
        exit;
    }

    // Export complete report to CSV
    private static function exportCsv($month, $year, $users, $attendanceByUser, $tendersByUser, $deptMap) {
        $monthName = date('F', mktime(0, 0, 0, $month, 1, $year));
        $filename  = "TBBA_Executive_Report_{$monthName}_{$year}.csv";

        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Pragma: no-cache');
        header('Expires: 0');

        $output = fopen('php://output', 'w');

        // Title Header
        self::writeCsvRow($output, ['THE BRIDGE BUSINESS ALLIANCE (TBBA)']);
        self::writeCsvRow($output, ["EXECUTIVE CONSOLIDATED MONTHLY REPORT - {$monthName} {$year}"]);
        self::writeCsvRow($output, ['Generated on:', date('Y-m-d H:i:s')]);
        self::writeCsvRow($output, []);

        // Table 1: Staff Attendance & KPI Summary
        self::writeCsvRow($output, ['SECTION 1: STAFF ATTENDANCE & TENDER KPI SUMMARY']);
        self::writeCsvRow($output, [
            'Staff ID',
            'Staff Name',
            'Role',
            'Position',
            'Department',
            'Present / On-Time (Days)',
            'Late (Days)',
            'Leave / MC / Absent (Days)',
            'Attendance Rate (%)',
            'Tenders Submitted',
            'Total Tender Value (RM)'
        ]);

        foreach ($users as $u) {
            $uid = $u['id'];
            $att = $attendanceByUser[$uid] ?? ['present_on_time' => 0, 'late' => 0, 'leave_mc_absent' => 0];
            $tnd = $tendersByUser[$uid] ?? ['count' => 0, 'total_value' => 0.0];

            $totLogged = $att['present_on_time'] + $att['late'] + $att['leave_mc_absent'];
            $rateStr = $totLogged > 0 ? round(($att['present_on_time'] / $totLogged) * 100, 1) . '%' : 'N/A';

            self::writeCsvRow($output, [
                $u['employee_id'] ?: 'TBBA-'.str_pad($u['id'], 4, '0', STR_PAD_LEFT),
                $u['name'],
                strtoupper($u['role']),
                $u['position'] ?: '-',
                $deptMap[$u['department_id'] ?? 0] ?? '-',
                $att['present_on_time'],
                $att['late'],
                $att['leave_mc_absent'],
                $rateStr,
                $tnd['count'],
                number_format($tnd['total_value'], 2, '.', '')
            ]);
        }

        self::writeCsvRow($output, []);
        self::writeCsvRow($output, []);

        // Table 2: Detailed Tender List for the Month
        self::writeCsvRow($output, ['SECTION 2: MONTHLY TENDER & PROJECT SUBMISSION DETAILS']);
        self::writeCsvRow($output, [
            'Tender ID',
            'Staff In Charge',
            'Project Name',
            'Client Name',
            'Closing Date',
            'Project Value (RM)',
            'Cost (RM)',
            'Selling Price (RM)',
            'Margin / Profit (RM)',
            'Status'
        ]);

        foreach ($users as $u) {
            $uid = $u['id'];
            if (isset($tendersByUser[$uid]['tenders'])) {
                foreach ($tendersByUser[$uid]['tenders'] as $tRow) {
                    $csvSelling = $tRow['selling_price'] !== null ? (float)$tRow['selling_price'] : null;
                    $csvCost    = $tRow['cost'] !== null ? (float)$tRow['cost'] : null;
                    $csvMargin  = ($csvSelling !== null && $csvCost !== null) ? $csvSelling - $csvCost : null;
                    self::writeCsvRow($output, [
                        'TND-'.str_pad($tRow['id'], 4, '0', STR_PAD_LEFT),
                        $u['name'],
                        $tRow['project_name'],
                        $tRow['client_name'],
                        $tRow['closing_date'],
                        number_format((float)($tRow['project_value'] ?? 0), 2, '.', ''),
                        $csvCost !== null ? number_format($csvCost, 2, '.', '') : '',
                        $csvSelling !== null ? number_format($csvSelling, 2, '.', '') : '',
                        $csvMargin !== null ? number_format($csvMargin, 2, '.', '') : '',
                        strtoupper($tRow['status'])
                    ]);
                }
            }
        }

        fclose($output);
        exit;
    }

    private static function writeCsvRow($output, array $fields): void {
        $safeFields = array_map(static function ($value) {
            if (!is_string($value)) return $value;
            $value = str_replace("\0", '', $value);
            return preg_match('/^[\\x00-\\x20]*[=+\\-@]/', $value) ? "'" . $value : $value;
        }, $fields);
        fputcsv($output, $safeFields, ',', '"', '');
    }
}
?>
